/**
 * UserAvatar — renders a DiceBear-generated avatar for a user.
 *
 * Always renders as a fixed square with rounded-full clipping to prevent
 * stretching or distortion. The avatar URL is generated by the
 * `userAvatar()` helper based on the user's username.
 *
 * Props:
 * @param {object} user      — user object (needs .username for avatar generation)
 * @param {string} className — Tailwind size classes (default "w-9 h-9")
 * @param {string} alt       — alt text for the image
 */
import { userAvatar } from '../lib/avatars';

export default function UserAvatar({ user, className = 'w-9 h-9', alt = '' }) {
  return (
    <div className={`avatar shrink-0 ${className} rounded-full overflow-hidden`}>
      <img
        src={userAvatar(user)}
        alt={alt || user?.username || 'User'}
        className="w-full h-full object-cover"
      />
    </div>
  );
}
